# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Grant Gannaway
email: grant.gannaway@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  [https://sites.google.com/site/grantgannaway/] (https://sites.google.com/site/grantgannaway/ "google site")
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: grantgannaway
github_username:  gannawag

# Build settings
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: G-JG1TVQ5S9W
    anonymize_ip: false # default
  
minimal_mistakes_skin: "dark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

logo: "/assets/image0.jpeg"

permalink: /:title/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  collection-archive:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # _collection-archive
  - scope:
      path: ""
      type: collection-archive
    values:
      layout: single
      author_profile: false
      share: true

author:
  name: "Grant Gannaway"
#  avatar: "/assets/images/bio-photo.jpg"
#  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Boston Metro"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/GrantGannaway"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gannawag"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/grant-gannaway-321ba326/"
    - label: "Google Site"
      icon: "fas fa-fw fa-link"
      url: "https://sites.google.com/site/grantgannaway/"
      
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include: 
    - _pages
  
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
